from keras.models import model_from_json
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.preprocessing import sequence
import re
from nltk.stem.porter import PorterStemmer
from flask import Flask, request, render_template
import numpy as np
app = Flask(__name__)



@app.route('/')
def hello_world():
    return render_template('index.html')

#@app.route('/handle_data', methods=['POST'])
#def handle_data():
    #feeling = request.form['feeling']
    #print(feeling)

    # insert model
@app.route('/handle_data',methods=['POST'])
def handle_data():
    feeling = request.form['feeling']
    data=[feeling]
#if request.method=='POST':
    #feeling = request.form['feeling']
    #data=[feeling]

    #Text Cleaning
    
    def words(text):
        return re.sub('[^a-zA-Z]', ' ', text)
    def lower_words(text):  
        return text.lower()
    def stemming(text):
        p_stemmer = PorterStemmer()
        stemmed = [p_stemmer.stem(i) for i in text]  
        return ''.join(stemmed)

    def clean_text(text):
        words_only = words(text)
        print(words_only)
        lowered = lower_words(words_only)
        print(lowered)
        stemmed = stemming(lowered)
        print(stemmed)
        return stemmed

    cleaned_text = [clean_text(x) for x in data]
    print(cleaned_text)
    
    #Tokenize Cleaned text
    num_words = 1000
    pad_type = 'post'
    trunc_type = 'post'

    tokenizer = Tokenizer(num_words=num_words, oov_token='UNK')

    train_text = ['i m sick of be here',
'what s the point of be sober',
'how to make yourself product there are some strategi to make yourself product',
'work at amazon for year wa the worst experi of my life',
'death to america',
'imag of thing convert to text',
'idea a sitcom about the live of actor who star in a sitcom',
'i feel so much academ stress becaus of my town famili',
'help',
'dae get anxieti when help custom at work',
'i am somewhat of a motiv mess',
'shop nightmar',
'thi say a lot about our societi',
'is cave water safe to drink',
'our purpos is to evolv as a speci leav the earth connect with foreign form of life on other planet and find the mean of all thi togeth',
'is there a light at the end of the tunnel',
'depress anxieti',
'alright',
'i gettin worri',
'i am bad at adult',
'thi post bought to you by reddit com a most silli websit',
'hot take video game are good in some context and bad in other',
'unfamiliar',
'i m worri no matter what i do i m a bad person',
'anxieti ha seem to make me complet incap of enjoy myself how can i learn to have fun again',
'nice rainbow',
'sorri guy no kaijun today but i have been design a toy in my free time and i just put the concept art onlin check it out if u like expect monster tomorrow',
'warn in minut a post will be post that will contain the maximum amount ghost',
'i cannot pass thi anxieti attack it s been hour now',
'quick drink thi there s no time to explain',
'would could and should are the most fuck word',
'sometim life suck',
'anyon who ha realli recov from depress how do u get better',
'how do you find a new dentist',
'there are peopl in thi world who will walk all over you then complain that you re not flat enough',
'what s the name of the emoji fill bot again',
'wahoo',
'break post is best',
'whi doe everyon dislik me',
'whi america s hors didn t have a name',
'sometim i just wanna watch the world burn',
'day in quarantin roma itali',
'i found out my sister might be asexu',
'real float hour who s up',
'pooki did yr concert turn out to be fun',
'tri it out',
'i keep get intens depress when i play video game',
'i m sorri but i refus to worship a crimin',
'if we could de cat the cat we wouldn t need to de claw them',
'will anti depress make me feel less ugli',
'and kjune cryogen orca hound',
'i wonder if the associ with a certain presid ha rais or lower the chees corn puff snack s sale stock price',
'do not go out in the sun it is tri to eat your youth wear sunblock even in door it is look for you help us blow up the sun befor it s too late for you',
'terrifi of fall asleep',
'when darl must be murder',
'advic need how to cope with anxieti about drive',
'that moment when your use a receptacl of some kind',
'all the thing she said all she said said',
'the displeasur of live with human an xl vent',
'there s no way russian bot aren t push anti trump pro berni now',
'not have friend make it twice as difficult',
'my ex refus to speak to me but still watch my snapchat stori',
'just me or',
'asdfghjkl',
'had a dream where i had a friend woke up and now i m realli depress',
'self serv tendenc lack of motiv lack of vital lack of ambit lack of empathi loss of integr social anxieti irrit lack of social etiquett lack of interest in life rapid memori loss and overal so much cynic within me',
'itt sum up your countri in one pic',
'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
'how do peopl with depress feel after be broken up with',
'i m cri',
'what do i feel in my chest when i get stress anxiou',
'what the',
'stop let your kid just go and pet dog or into dog park without proper teach of how to approach dog',
'philosophi of humor stanford encyclopedia of philosophi',
'whi is bitcoin the trend topic of the centuri a detail analysi',
'the nois in my brain',
'a lot of us are feel stress right now due to covid health ha been a problem for some peopl while other are deal with their job be suspend if you are frustrat with the current situat then feel free to vent with thi playlist of energet music updat often',
'quarantin ha been make us all a littl crazi',
'feel like i m griev dure thi anxieti attack but i haven t lost anyon doe that make sens',
'tri to get to a better place ani advic would be great d',
'don t mind us just touchin tip keep scrollin',
'smol pig no photoshop',
'it s more bless to give than to receiv',
'what the actual',
'i want to kiss waluigi',
'went to the er for a panic attack feel like a mess',
'i haven t taken testosteron in a while and feel my entir person is shift',
'whi do black peopl say ak instead of ask pronunci on other word is fine but specif thi word is butcher',
'wanna know who i dont like',
'best natur remedi for stress',
'i final mention it and i feel so much relief now',
'damn it time to come clean',
'found a tereibl way to feel happi for a while',
'what can i do in my daili life to tri and help reliev some of my anxieti',
'how to get help for drug abus rehab for an onlin friend',
'tag yourself i m the zergl smokin a big ole cigar',
'one upvot and i ll wage a one man war against the netherland and all the dutch peopl',
'if you upvot thi post then texa will becom like big citi liber california',
'just saw the thick anim girl in the kfc date game and i think will burn down my local kfc now',
'sinc it s r just post',
'let s go for a walk',
'thi is just a poem i made out of frustrat of what the world like and am too embarrass to show peopl out of fear of be made fun of hope you like it',
'i m scare of thi push me over the edg',
'i might have addit to porn',
'good',
'find the right distress toler skill for your situat',
'month off weed',
'sever anxieti and compar self to other',
'i m a failur i guess',
'ha anyon felt like thi too',
'anyon out there have young kid and been to rehab befor what did you tell the kid how can i tell my year old that i am leav her again',
'good morn',
'seek particip for an interview about stress manag opportun for a month free trial of neolth',
'thi is a pictur i drew of a fish that ha arm',
'the averag chest hair post',
'is there a subreddit for help comput tip that a lot of peopl probabl alreadi know but you just learn',
'new discoveri discov import inform scientist give me moneaey',
'hey check out what i can do',
'how do i stop overthink',
'intrus thought about lung damag make me miser',
'thi is an edibl post',
'i don t know if i m just sad or depress',
'anoth imag to use howev you want',
'it turn out post is bee',
'i just want to get thi off my chest',
'i enjoy go to r longdist just to tortur myself',
'i m hurt for my sister',
'think about quit my job',
'hey r addict thi is my stori i hope you find some use in it if anyon ever need to talk about their addict i am here to be a non judgment ear to listen i don t care what color gender sexual orient idgaf if you re from mar i will listen to you and tri to help',
'anyon els still get anxieti over the thought of school',
'luxuri foam soap',
'fun idea instead of throw ur garbag in a trash can just throw it directli into the ocean to save fossil fuel and stuff',
'should i delet my account un offici poll',
'hot new idea',
'i don t mind be downvot when i know that i m correct',
'if time travel is discov one of the best thing to do could be fast forward contact between europ and the new world as well as publish today s knowledg of health',
'i tri to escap reddit by delet my account but i came crawl back and made a new one',
'when did you realis you d hit rock bottom',
'heck',
'clonazepam',
'ernst busch der heimlich aufmarsch',
'i like the old day but not all the old day',
'took diezapam x mg think last dose wa like i have codein for restless leg but scare of the interact',
'i have import meet come up about my job how do i stop think about the neg outcom and avoid burnout befor the meet happen',
'workplac anxieti',
'be ask to send a pictur photo of yourself',
'i m too tire to achiev anyth through the day but i can t achiev anyth dure the night what should i do',
'do we realli need the whole earth',
'go shop',
'i cant take critic anymor',
'one day googl and facebook might decid f it and just post everyon s privat messag and email',
'ix inecraft',
'suggest for a cocain addict digit meet',
'i need to get off reddit',
'updat i can t take selfi in my apart',
'if you had a friend ask you to stay sober with them so they could get clean what would you say',
'sponsor friend',
'i think my life would be easier if my atom were spread over a wider area',
'age is a matter of the mind if you don t mind it doesn t matter',
'worst two year of my life',
'i don t know what els i can fuck do to even my with peopl form my past',
'give himb a kiss',
'work work',
'one of my greatest fear is for me to final be get over my depress just to have societi collaps around me make none of it matter anyway',
'i wa around peopl today',
'if i owe a busi money they expect it immedi if they owe me money they ll get it to me in two to six week',
'way to turn quarantin into qualiti time with the kid',
'burden',
'just stay posit',
'dae love their partner s famili more than their own becaus your own famili is one big yike no advic want',
'a littl late night poem',
'pleas updat your person style accordingli',
'what amus you today',
'therapist say stop isol it s the onli way i can cope',
'you reddit',
'someon post thi excel video on tumblr you must watch it now',
'the du liti of m n',
'drug dont seem to be help with my deep emot pain anymor',
'test post',
'workplac snarki',
'time to scream',
'pam i ve had thi phone number for year now can you pleas stop give doctor attorney creditor and your church friend my number if you don t i m gonna start text them meme',
'what are some idea i can replac with televis',
'i got misgend and it wasn t the wors thing in the world but i m worri that i m gonna spend the next week spiral',
'sever anxieti from chain smoke weed kept hunt me my mind is wire to certain chain of thought no day pass without me get sever anxiou',
'logan paul is stream fortnit',
'how post r made',
'what a cute hob',
'anxieti and pregnanc',
'it s actual in less than week were real lucki to be aliv and just want to say holi',
'distress toler skill improv',
'dam',
'friend are you okay',
'here s a littl frog with a leaf umbrella for ya ll in these stress time',
'what if it s all just one bear',
'when do i stop tri to fix myself and start to accept myself for who i am',
'iren',
'who thought reason whi wa a good idea',
'my brother sent me anoth video',
'import video',
'it the postlic open up',
'can your televis make you rich',
'so my therapist of about year just hung up on me and said she isn t have my session with me becaus she won t deal with a panic attack',
'i hope to you didn t care as much as i did',
'i just forgot my pet name for you and all those promis i said i d keep',
'if you had to choos between',
'resourc that provid afford access to high qualiti therapi for anxieti',
'i m scare my partner and i might be reach a dealbreak in our relationship',
'pole are a new kind of post',
'sword battl of the master',
'shoutout to the moonrat the onli speci other than hebhob in the taxonom famili erinaceida they re like hebhob cool cousin',
'i fuck up',
'is thi a rhetor question',
'look rough',
'cocain addict and what action to take',
'bear of the polar varieti',
'when to take seroquel if i need to wake up for work at around am everi day',
'excit mistaken for anxieti',
'guy check out the book subtl art of not give a f ck by mark manson i feel like it wa written for us',
'i feel like my time is almost up again',
'noth s the same anymor',
'arpest tool in the shed she wa look kind of dumb with her finger and her thumb in the shape of an l on her forehead well the year start come and they don t stop come fed to the rule and i hit the ground run didn t make sens not to live for fun your brain get smart but your hea',
'i m scare of how danger lone i m about to be',
'she left me after year with no explan mayb i m better off',
'lpt in war it is arguabl more import to protect your ass the most power bodi part than it is to protect your che area therefor you may want to wear your armor like thi instead of in the tradit way',
'confus',
'i made a gingerbread hous the other day that is all',
'i hate when peopl say that im afdict ti video game',
'addict person',
'today i quit juul',
'such an ahol',
'am have problem choos profil pictur',
'relax music stress relief medit music yoga inner peac sleep',
'i had to move back with my parent hate be here constant physic symptom of anxieti',
'quit the job becaus of anxieti',
'i find out thi week if i m go to be abl to leav a toxic situat sooner rather than later',
'end',
'it hurt',
'i m in spencer s right now and i hate my life',
'hastagrelat',
'am i the onli one who scare of think about weird thing bear other think they know what im think',
'sometim i think johnathan davi',
'don t worri about it just accept it',
'i might need help but i am scare and don t know what to do',
'hi how is your day go',
'if a compani can print or fabric more of your rare item it s not rare',
'realli been feel thi one late',
'i don t know if i m suppos to give up',
'i have decid that berri are bullshit',
'tail circa',
'i might end my hospit career over thi mask bullshit',
'so my mom bought compound bow',
'i don t know what i would do if my roommat die',
'whi doesn t mario ever have ani plumb relat power or quest like mayb a wrench weapon or some leaki pipe puzzl serious',
'i just rememb how much i love the melancholi of haruhi suzumiya',
'what are your prime tweaker moment',
'wa anyon abus dure their use',
'an actual quot from the novel dracula',
'i have borderlin person disord',
'i don t know what to think anymor am i overreact',
'to the nurs that save my life',
'coffe',
'golden mean ha been one of my biggest life lesson i realiz that what matter is to find a balanc between wealth health and relationship you don t need scarciti nor excess what you need is balanc live a fulfil life',
'insight',
'what are you have for dinner',
'for peopl who have anxieti how did you control it',
'googl hous and the amount of karma you have the first one to show up is your futur hous',
'check out my new song share if you like',
'turn on the sound',
'is there a way to know if you need to be on medic or not',
'lost my soul',
'warn flood warn cancel in event of a flood contact r just post and request a belat flood warn',
'ayi lmao',
'what s your favorit font',
'i have no reason to be here',
'america i hope i die',
'relaps',
'some day vape could be an old peopl thing',
'ha anyon conquer marijuana addict',
'trash raft',
'how to make right decis in life',
'guy i ve decid to end racism',
'it s kinda weird that i ve never met a scorpion',
'despair from memori laps',
'how did you manag the first hr clean',
'how to stop feel anxiou if the cat doesn t come to us anymor',
'it fishi soap',
'fuckin hate the word hooman',
'i want to stop but i m afraid i never will',
'they say that eat chees befor bed give you bad dream',
'i accident kill a babi mous and i feel horribl',
'sick of stress',
'today i heard someon say big dick energi out loud just out in the world',
'girlfriend is gain weight and it s hard to get an erect',
'who knew not build a comput but manag it after it s been built can be so stress',
'damn ive dinal done it arent i',
'i need help',
'sobrieti and the repercuss of long term stim abus',
'grate for still be aliv hope thi messag could benefit you too as it did to me',
'urgent',
'goodm rning everyon',
'my dad is sick and not take thi serious at all',
'we re ask you to fund our kfc desir',
'learn how to bring inner peac for lifetim',
'some of y all don t know when feminist are and i ll give you some few pointer',
'jmsn is the coolest mf n dude in music',
'scare about everi littl thing due too your truli anxieti i went to the dentist today and they had to do fill they gave me lidocain which i didn t want i am now afraid i ll die and go into cardiac arrest it s been like hour sinc the inject am i okay also the numb went away',
'i ve decid to use you guy to tri out my meme',
'just wanna say happi cake day to me',
'i may need to get blood work done and i m absolut terrifi of let someon stab me and potenti f me up for life',
'me when there no hot water',
'pleas respect ryan',
'how do i talk to my parent about depress',
'let me in plz human',
'when rotari phone were use you could dial wait for a dial tone then dial and hang up and your phone would ring',
'i am happi',
'is it still breakfast if you eat it dure dinner time',
'how do you get over the anxieti over peopl chang or cancel plan',
'im tri to make a meme in a post format',
'who the invent golf',
'stupid me stupid me',
'am i suffer from stress or anxieti',
'idk whi tbh',
'a squid stori idk rli pl',
'twelv inch',
'how to be creativ when you are stress how to come out of stress within minut',
'happi america day',
'whi do i open my mouth',
'broke five month of sobrieti feel horribl physic and emot',
'i made thi imag like a year ago and there ha never been ani reason for it',
'septemb ha grace australia',
'walki',
'follow the rule',
'i feel miser',
'bore post but thi is my new favorit album ever and i ve been listen to it non stop becaus it just fit the mood for my entir life rn and the album art is great',
'irrit so mani peopl love unfriend dark web and yet herefitari got trash on',
'good news thread',
'depress it symptom and way to overcom from it',
'i m get stress over how i ve been treat my how life',
'i just found my boyfriend s paraphernalia',
'dude',
'i am wast time by post',
'well meth we had a nice littl run you and i but it s time to cut tie cross post side i realli need all the advic tip trick and secret to get through thi',
'the stori of doug felon drug felon',
'the chair on the bridg of the enterpris don t look veri comfort whi have two separ cushion with a space in the middl is thi some sort of advanc chair that we simpli don t have the technolog for',
'i feel so broke and worthless',
'just found while clean my room',
'i m just a guy have a good time post on the internet',
'what s the smallest thing you ve fallen apart over',
'i fuck up real bad',
'the hurt',
'day clean from dxm i don t think i m gonna stick to thi',
'i ve thought of an idea for stress but i wanna run it by some peopl first',
'how do i commun with my parent',
'i text my crush who and im about how i have a huge crush on her just befor she s about to be gone from my colleg',
'in gener i have been p happi with my sub scription to dropout tv',
'i think astrolog is bullshit but mayb it s becaus i m a capricorn',
'i hate calc',
'addict follow grief',
'been feel oddli hope late would love to hear some success stori to pump thi hope energi anyon',
'feel low and dumb',
'i still need ani random subject for episod ani chanc you can help me out',
'pregnanc or anxieti',
'day sober and day free of porn addict struggl to quit fast food have no motiv to do anyth',
'gone again',
'hi how is your day go',
'is there ani music you know of that almost nobodi ha listen to',
'sword of the spirit word of god full armor of god for spiritu warfar ahavaha',
'i m back',
'caterpillar march',
'need a hug',
'i m scare about go back to school',
'i love overwatch and i hate everyon who play it',
'xbox is better than ps',
'i think my sister is on the path to becom an addict how can i help and get through to her',
'doe anyon els not quit believ it anxieti',
'some meme',
'if you even mention the spongebob episod wormi i will go fuck insan',
'can you be sexual incompat with someon and turn off by the idea of anyth explicit involv them but still find them attract in a way',
'new job anxieti',
'what should i do',
'i want to shove creme egg up my ars and pretend i m a chocol chicken',
'gain pound in year huh can i be proud',
'dentist appoint anxieti',
'the big game',
'i feel the need to say return of the jedi as return of the jeddi just to tick off my friend',
'let s have a movi night',
'tanscendent album u should listen',
'hi',
'no good day in sight',
'ive lost the most import meme these meme gave me comfort and satisfact and scratch my itchi brain now what fk',
'male get eat disord too',
'excess intrus nostalgia',
'famili and loss',
'i wrote a thing',
'you see i m a bilingu',
'i made art',
'don t let missil prolifer',
'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
'will a hour long walk wors my anxieti',
'stress at work ani thought',
'i hate my famili and i m jealou of those with normal and happi one',
'whi ye i would',
'stress manag is key',
'if you had and you had to spend all of it in hour what would you do with it',
'man have you guy seen scorpion',
'enjoy it while it last',
'no sleep ever',
'i broke up with my anti feminist boyfriend',
'social is cool but then i start feel inferior to other becaus they have more life experi and inform than me',
'i m just so stress about life',
'i spill my qdoba leftov on the floor',
'my teacher refus to put in my grade',
'is the physic stress a thing not mind onli bodi',
'good book to pass the time with',
'i woke up and saw my crush leav a one night stand on snapmap so i went for a run hope to randomli bump into her and now i feel like',
'ever sinc quarantin start i ve had weird new way of my anxieti manifest and i have no idea of what to do',
'how tf do they grow mash potato anyway',
'just post',
'first post been clean of alcohol for over year now and thi is the first day quit weed and i m get realli depress but i know it s for the best ani suggest',
'the paradox of feel alon but not want to initi friendship',
'bizarr bedtim secret for an amaz night s sleep',
'weekend dad',
'first day sober sinc middl school',
'welcom to my candi store',
'i want to cri',
'i can t control ani of my emot anymor',
'one question',
'fix up look sharp don t make me get the blitz out get dark hear the bang see the spark duck down lay down just fix up look sharp don t make me get the blitz out get dark hear the bang see the spark duck down lay down just',
'damn i just lost the game',
'the true th',
'rude word',
'how to deal with work stress',
'i can t hold my ring finger up and keep my pinki finger down on either hand',
'oh gosh oop i just drop one of my skull haha',
'im vegan',
'feelin bore',
'get out of your head saturday night bender feel alon or come down reach out get out of your head addict is not a moral issu you may feel like a bad person but you are not',
'is there ani hope of recoveri for an isol meth addict who even ha a partner',
'i m hide don t tell them i m under the blanket',
'kobi if you can read thi come back',
'need help to quit smoke',
'an imag from the vault new york citi octob',
'day',
'i bet i can make you want to do thing you ll regret',
'i m so scare of die that i m bare live',
'what s the best kind of sparkl water',
'am i fall behind in life',
'the car from the movi car',
'f these entitl compani hr',
'nccih on stress fact to know about relax techniqu for stress',
'i don t even know what i can do anymor',
'year ago we lost robin william to suicid pleas get help if you re head down that road',
'i walk my dog nake everi morn and love it',
'pl read',
'anyon els alway tire',
'i m tire of life',
'just sleep',
'we apolog for the confus',
'stress about summer school work',
'me irl',
'vote up if fork shoudl be renam to frok offici poll',
'my gf of year ghost me month ago and sometim it too much for me',
'help with brain fog',
'i feel helpless in the fight against depress',
'everi decis i ve made over the past month ha been wrong',
'hey katrina yeah i see you read thi',
'i have job interview and a dentist appoint on tuesday',
'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
'do you think cow stand by the side of the road silent solv quadrat equat for their own amus',
'i don t know whi my mother doe thi to me',
'pleas open thi post to agre',
'owo',
'i wanna post',
'i have a warrant for pshower s arrest',
'physic affect of anxieti',
'how do peopl who don t use phone case even use their phone',
'just ghost',
'im high again',
'should i tell my father about my chronic stomach pain due to stress',
'dude wtf',
'healthi addict',
'make dog be cop is anim abus imo',
'tri to quit soda',
'what thi year brought sorri it s a long one',
'the problem with the world is there are actual two world',
'the happi mother s day post i won t make on facebook',
'sad time room',
'crave self accept you need to start with a littl honesti',
'after you hit year of age anyth goe',
'how to get anyth you want in your life',
'crunchat me cap n',
'i m averag in everyth i do and it bother me a lot',
'turn the sound up tippi tap',
'you wear a disguis to act like human guy',
'strip mall should be convert into countri club',
'so much anxieti caus by the internet help',
'my boss ha been stand at my desk for nearli half an hour tell me about how ineffect gun law are and i kind of just want to cri',
'let peopl abort',
'what is the hotkey to do homework',
'illeg build techniqu',
'depress feel like you are fall from high edg for your whole life',
'get out of a toxic relationship struggl with anxieti',
'but i don t want to do anyth',
'may i be born pleas',
'the tuba in the string section',
'i m sick of everyth',
'is there such a thing as quit too mani addict at onc',
'the zodiac killer would have been much less scari if he wa the zodiac kisser',
'upload is so easi the post basic write themselv songular',
'i am consist enjoy make music again',
'in a bar at am with peopl be drunk and social and the news is on tv',
'warn thi is a polit post',
'cant wait to sit at a tabl and listen to peopl eat for half an hour',
'lost a beauti tragedi that most would say good riddanc to',
'someth weird happen today',
'climat chang is go to kill us all',
'freelanc',
'is rock bottom a myth or the truth',
'i tri to buzz cut my own hair and it wa a disast luckili my parent help me out',
'strang addict',
'i want a long and happi life but i don t think i can stick around',
'been listen to experiment music for so long that typic stuff sound fresh and interest',
'i had an inappropri relationship with my aunt',
'whi do we fail to quit smoke',
'first day on citalopram celexa',
'liter never interact in my life with you but ok bro',
'disast in the make',
'you ever have an aw entiti in your life and then they re not near you anymor and everi thing s good',
'a messag to peopl who get realli mad at doggo speak post',
'my murder remain',
'there are more post',
'fun fact',
'smell a book',
'yolo is just a number',
'the game',
'gf dump phone in toilet the second time everyth work includ touch except display manag to get a backup from rememb where the button are and gave her my old phone',
'just woke up veri sad and scare',
'what do you look for in an addict counselor',
'what the do i do',
'weather updat my in law are back togeth again',
'mayb the real friend were all that treasur we found along the way',
'old town road remix',
'don t be stress and becom strong in life',
'weed and lazi',
'toler to sertralin',
'everi sinc my mom die year ago i f cannot stop smoke weed send help',
'cow are so smart and funni',
'i now have to complet month worth of school work in two day becaus i procrastin everyth dure quarantin wish me luck',
'you are submit a text base post speak your mind a titl is requir',
'smilin allig',
'my cat take hr to feed wet food',
'pree sister swallow a donkey s eye',
'fun fact if a top bun is attempt and leverag forward and held in place with a red pen it kind of look like a pompadour',
'everi just',
'psychemetr',
'after battl with comput troubl all day ive decid to reject technolog and move into the mountain',
'i hate coca cola advertis',
'i am so pathet',
'most post are creat and perceiv with the sens of sight what other sens would you like to creat and perceiv post with',
'what i don t like about the internet',
'how to stop stress eat',
'day left',
'how on earth do i stop overthink about everi littl thing',
'chelsea man is a hero',
'just leav thi here for you to decid',
'i m learn to play guitar',
'like sand through the hourglass so our the post of our live',
'updat loneli is the reason i can t stop use',
'cat splat on back',
'i dont know what to do',
'chest pain pressur from anxieti',
'best kobe play',
'test',
'free imag use howev you want',
'brother julia beverley',
'a podcast about anxieti',
'today is a sad day',
'anyon getth feel reddit is drive us the wrong way',
'record',
'whi do you bother discuss polit and bash on those who don t think like you do',
'the',
'i m good at apolog becaus i do a lot of bad thing',
'where the lamb sauc',
'just want to share thi pic the bird look realli glamour',
'my hair is way too long',
'i found out whi i have a thing for asian girl and i don t know if i could ever go back',
'aoc saw my instagram stori',
'in countri like india and pakistan rape is consid both the man and woman s fault do you agre',
'folk we got em',
'i got ghost again',
'homework',
'i ate all the carbon there s none left',
'where the heck did i park my car',
'kaijun eldritch tri lineless thi time and b w for valu studi max spooki',
'look for some advic for the everi day',
'school stress',
'worri about the littl thing too much',
'thi is my dog salli she babi',
'extrem separ anxieti feel paralys',
'help me',
'i am the onli person in the world who is real but i love all of you littl ai simul thing anyway',
'funni how i m sick',
'peter s soul relax cosmo relax music',
'i said someth inappropri on facebook and got flag now my brain is race',
'experi with prozac',
'pleas note',
'full tutori the law of attract how to manifest anyth you want',
'you can post if you want to',
'i m slowli turn into an agoraphob',
'stress vs anxieti',
'you pop open the box you see if the cat s aliv or dead easi i realli don t see what s so hard about thi',
'realli bad anxieti and deep fear about the futur',
'i am addict to reddit',
'i stole money from my mom and now the bank is involv',
'i m so fuck done with open up to peopl',
'these coronaviru conspiraci theori are realli scare me',
'scare of me or my dad have sudden heart attack',
'societi ha been hide the second half of shoot star from me for ten year',
'whi do peopl keep make link to r',
'enough is enough',
'i want to get over my anxieti and be abl to talk to peopl',
'haven t work in sever month but start a new job tomorrow',
'tri soylent for the first time today',
'my april fool circl passcod is whatisuppost',
'my friend ha a trophi wife but appar it wasn t first place',
'get sober again',
'i still think about you even though you re an asshol',
'a griev snow fall in the dead morn stray dog howl as footstep pierc the air i walk with the weight of the univers on my shoulder yet an umbrella that hold onto the dark is all i have',
'i m f flunk out of high school and i feel like i m trap in my own person hell',
'i have a confess to make i realli mess up',
'click here to summon the dude',
'i did the orang justic fortnit danc and my ankl crack like thunder',
'candi ken a tissu of lie prod kollektiv sandgass',
'whi your life is not the way you want it chang it today with law of attract mind',
'toluna paid survey review i need your feedback',
'shoe holi f king shoe omg shoe',
'hubbi broke quarantin to get weed',
'it feel like work',
'anyon play ani new game no spoiler',
'the knee is the oe',
'what if she s fine it s my mind that s wrong',
'the fire depart will not come to get a kite out of a tree',
'i like coconut so a coconut water drink can t be that bad right wrong',
'saw a ladi drive her power wheelchair in the center of the oncom lane',
'recov from stress and anxieti natur through write',
'just third wheel a doubl date i feel aw',
'how can i be a good friend to someon in the midst of addict',
'weird find',
'thi is all wrong i shouldn t be up here',
'i m extrem scare of insect and saw thi big cockroach in my room',
'is anyon conflict about visit grandmoth for mother day',
'i m rememb how hard it is to motiv myself alon',
'tw tw tw twenti nineteen twenti nineteen',
'just post ha been invad by alien',
'doe anyon els feel so extrem happi with everyth in their life but deep down feel like they have a sad soul',
'doe the rain cloud make anyon els sever anxiou',
'i have acquir the heb sock',
'i won t last long on thi path',
'r avoid and r e irl when combin contain all the secret of the univers',
'just trap in my own live hell of a bodi palpit non stop i can t stop think about my heart i feel it at all time like it s massiv deep breath trigger it lie on my side alway breathless i ve had heart test all ok',
'break news',
'spiritu warfar the full armor of god for battl against enemi point to thi one man',
'found the chad fork',
'so the point is just post right',
'i am worri about the coronaviru pandem',
'my local facebook marketplac is alway interest weird mid evil style furnitur left in a rental unit from previou tenant make offer',
'trademark the name mayonnain t for my hypothet brand of vegan mayonnais',
'hi ignor me',
'may th he love a visit from the garbag ape',
'wow im bore',
'i have so much troubl stick up for myself and it undermin my alreadi low self esteem',
'i need new way to cope',
'whoever made the pacif ocean you re fire',
'ok so appar there s a possibl that i m not ugli',
'how do i cope with routin disrupt',
'how to switch off',
'saw my best bud magpi again today at uni',
'i need to post about pp',
'tell me that the pain go away',
'should i delet my account',
'bruh',
'my girl dicc',
'my bf told me he would give me if i could stay happi for a whole month and i don t know how to feel about it',
'finish the sentenc you can onli comment one word per person',
'i caught a terrorist said no tsa agent ever',
'not go to attempt to eat just one larg meal a day ever again',
'jehovah s wit are like girl scout',
'would life be worth it if you didn t get to be a kid at the begin',
'so my anxieti ha creat fear and im not sure how to overcom it',
'i just gotta say that everi time i see someon comment or make a post say oh how the turn tabl i wish they get tie to the back of a truck and get drag mile in front of their entir famili extend famili includ',
'forgot to set my alarm urgh',
'i shoul be happi in my birthday and im not',
'i think imma start practic split while i entertain myself on reddit youtub mobil game etc',
'do panic attack symptom linger',
'your bodi is your own fault',
'don t think i ain t seen you postin here',
'cake day come share my cake with me',
'can t sleep for a week becaus onli job i m abl to do right now is at stake',
'almond milk',
'common stressor that affect peopl s life',
'whip scream',
'it s disgust how mani peopl don t understand how debilit depress and anxieti can be',
'do you ever get a random urg to play a game you haven t even thought about in year',
'sooo i got out of exam',
'just',
'daili check in',
'postign onlin',
'how far gone am i',
'it s clear that we are deal with veri stress time right now if you need some time to get away from the stress then feel free to check out thi playlist of chill music by mainstream and indi artist of differ genr',
'pew pew',
'dear reddit pedophilia isn t funni',
'kjune i shorten it becaus im tire of type kaijun but im type all of thi and i also just type kaijun in full just then so it wa liter for noth anyway typhoon',
'i feel like all my friend hate me',
'forevermark their diamond ad disgust me',
'the first charact of the enron wikipedia page',
'it s my cake day i guess',
'say cumbria without the bria',
'freak out about cognit damag',
'so mani post so littl time',
'look at my cute notebook i just bought',
'addict to sh',
'i need help doe aa meet work',
'ye',
'doe anyon els find the snoo profil pic kinda cute',
'help i might me in the wrong here',
'i sat down next to thi girl minut ago but now i m too shi to say anyth to her',
'bought an oximet the help with anxieti but it s not help',
'testpost',
'i hate wake up',
'i have to question whether i want to live in a world that produc the movi showgirl',
'over it',
'i ve been have an existenti crisi sinc i turn',
'i don t know who need to hear thi but',
'how can i forgiv my sibl',
'follow the ruless',
'lexapro question',
'what should i expect in detox iop php residenti sober live',
'peter s soul relax cello piano and harp relax music',
'new job is shoot my anxieti through the roof not sure what to do',
'how do you know if you re still depress',
'depress long distanc boyfriend might want to end thing due to my need for our futur help',
'slimepunk celebr',
'in botani a tree is a perenni plant with an elong stem or trunk support branch and leav in most speci in some usag the definit of a tree may be narrow includ onli woodi plant with secondari growth plant that are usabl as lumber or plant abov a specifi height',
'my boyfriend od d and die at my hous',
'i hate my brother',
'doe anyon experi short of breath without a clear caus effect relat',
'sad post',
'neuroscientist discov simpl techniqu to reduc stress you ve never heard befor',
'tranquil spirit stress relief music posit feel and energi',
'how to distract yourself from overthink',
'have a univers induc panic attack',
'my life s go downhil',
'i ve got',
'my thought and feel',
'graduat a year ago still unemploy',
'i love make thi soup',
'what is a good gift to get my brother for xma',
'just look for support or someth',
'ignor if pshower',
'my mother blame me for be sexual abus as a child and my dad never protect me',
'watch a video about weight loss gain appar men gain weight in the chest and belli area women gain weight in the everywher liter everywher',
'i pass',
'buspiron as need',
'hello i am guy who tv',
'uniqu way to care for your mental health when you re stress',
'anxiou and live without ani support',
'new music video about the road to recoveri',
'usual my music ha that aggress underground vibe to it so i tri someth differ with thi one i realli put my heart into thi one realli give you a piec of of me everybodi feel stress anxieti could be you a friend co worker or famili',
'window vs gnu linux',
'am i depress or just sad',
'she doesn t feel for me the way i feel for her',
'i realli want to cri',
'sometim i want to be rich enough so i could throw my phone like a shuriken at a person s forehead and not worri about it break',
'i feel like one day the gener that call everyth cancer is gonna see an uptick in actual cancer diagnos and realiz it wa kinda insensit to use it so off handedli',
'stop take stress about money and start save',
'high profil rapist mari kay letourneau ha die and she got away with so much damag',
'stress burnout breakdown thank to my job',
'i m scare i ll cave thi weekend again like i did last i worri i m hook on cocain pleas help',
'm ska m ska v rf di gl z an di vant r slant st a n n s lant h h h h h',
'live with constant rumin',
'the insid of thi flower ha zebra stripe',
'hau i feel wh en ieat th ebean btw j cole went platinum with no featur',
'what is my addict',
'weed and medic',
'i see',
'for everi upvot thi post get befor i wake up i will pet each of my two dog onc',
'ememm',
'is thi a good idea',
'meet my altern person hi name is dexter a stori of denial',
'want to get into a sport but worri about seriou injuri',
'burnout cure',
'i have zero self control',
'help me im confus i cant beat it',
'cello thunderstruck',
'everi day liter give me more and more reason to just give up on life',
'spooki month is final here',
'what is the longest name you ve ever seen with the most syllabl',
'my countri is open back up and i m terrifi',
'be your shelf',
'i grew up with veri littl money and now i get anxieti everi time i buy someth non esenci',
'it never end',
'mmmmini minni the ccat',
'you know when your parent suddenli say noun verb and you miss the first half of the sentenc so you say what and then they say pronoun verb or just verb and you re like',
'i vote',
'fun fact the word pixel is a contract',
'i m stuck and stress i don t know what to do',
'thinkin about thi dude',
'my problem are weird a littl',
'lost a beauti tragedi that some would say good riddanc to',
'busdriv eat rich prod by kenni segal dir brent weinbach busdriv eat rich prod by kenni segal dir brent weinbach busdriv eat rich prod by kenni segal dir brent weinbach newest post ever for at least a few second but that snotal',
'in the s in ohio my great grandfath got in troubl for ride a cow dure school hour',
'everyon pleas give a round of a plaw for my friend anni',
'peopl don t realiz how similar coffe is to chocol',
'i don t have scar on my wrist',
'can t wait to get my new pc',
'thi past month ha been one of the worst time in my life',
'found porn on my grandpa phone',
'actual i hate bartend all the time',
'when i wa a kid i saw a drop of water on the tv and thought just mayb that if the whole screen wa wet there would be an entir differ show that i could watch',
'i want to stop drink and smoke',
'hey check out these bug eye i just made',
'i need help with stress',
'bucket hat',
'ye i do be simp sometim mind ur beeeskne',
'i have a question',
'do you ever just spend half a year set up a joke',
'tumblr p ykqceop vr dsw',
'drink mask',
'bap bap bap bap bap bap bap bap bap bap bap bap bap bap bap bap',
'anxieti due to someon els s anxieti',
'feel bad even game now',
'i bought some silkscreen suppli help me with some tshirt idea',
'hello who here like tost',
'cee lo epic battl',
'wish my famili would be understand of my recoveri and support me by leav me alon while i withdraw',
'i need advic i can feel myself crumbl and i don t want to slip back i would realli appreci your help today',
'my brain is broken',
'the curs of bobbi lane',
'subconsci anxieti',
'leg',
'anyon have experi take suboxon and wellbutrin togeth',
'revers microwav',
'i ve got some realli bad bodi imag confid issu and have serious been consid some mild cosmet surgeri',
'the cure to rid societi of all it ill',
'one time we found a hous where the backdoor wa lock but miss a doorknob and my hand wa small enough that i could reach through the doorknob hole to unlock the door so we could go insid and we did',
'im gonna yell',
'think is hard',
'all berri are berri',
'onlin date is complet broken',
'roommat is a recov alcohol that start drink again',
'my life up until now ha been a slow and hesit answer to the question are you readi to live alon',
'my neighbor is obsess with money',
'i m exhaust',
'i don t sprech deutsch',
'don t you love it when you post the same thing day befor and it doesn t get a singl upvot',
'cri in the offic bathroom',
'enivrez vou',
'i need some help',
'lesson i have learn about life late',
'green egg and ham but instead of green egg and ham it s a guy tri to invit you to hi church and it end with you awkwardli chuckl and say mayb one day',
'some time you just gotta post even if you got nothin to post about yknow',
'help',
'the tree outsid my window is in bloom',
'i made thi post to cheer up yuliya again',
'thi is not where i pictur myself',
'think about a new usernam how doe thi strike you',
'what is stop you from receiv and give love',
'thi thread is the swear zone post swear here',
'i love eastern philosophi and spider it piss me off that white supremacist ensur i will never get a swastika or spider web tattoo asshol',
'the idea of end thing is all that make me feel okay anymor tw',
'to the singl and or unsupport mother happi morher s day',
'scorn flake',
'ani help translat the label on these jar of mysteri they re in cyril',
'look like im goin back to rehab for the th time just finish the rd in decemb',
'how the hell do teacher do it',
'effortless can be a good or a bad thing',
'post',
'hey guy new to reddit im yearold mate addict to cocain for year',
'if you could make anyth in ani medium what would you make',
'i have a drive lesson today',
'sever symptom from melatonin and hydroxyzin',
'what is up with these ryan post',
'ahaha i still want to die',
'endgam spoiler',
'i m listen to an interview with a garag punk duo and they were just ask their influenc',
'yesterday i went to the er two time becaus of my anxieti the first time wa noth that bad the second time my entir bodi froze up it suck ass becaus now my anxieti last thing all day instead of just last in the morn',
'eat icecream with a fork becaus ive given up',
'depress is ruin my life',
'it s time for band practic',
'over think is one of the reason behind depress learn how to stop over think and reduc the stress',
'yep',
'i don t want anyth anymor',
'the exist of primari and secondari school impli that there is a tertiari school',
'i just can t deal with thi anymor',
'do all male mammal have a prostrat in their butt',
'whi do success peopl have to be so goddamn condescend',
'i wa promis centimet but i got instead',
'kaijun that s all from me everybodi been a long month but it wa veri fun i hope you like my stuff',
'can t quit meth',
'i need a smoke buddi',
'ask not whi the addict but whi the pain',
'what the is r gendercrit',
'shoutout to my ex',
'peter s soul relax piano for sleep relax music',
'idk whi i m have a hard time deal with my anxieti',
'drink make me crave cocain',
'ptsd or mayb just anxieti',
'life ha taken a better turn for me yet i still feel hollow and empti',
'frustrat by the phrase happi is a choic',
'food',
'hobsferatu',
'whi dose lean make me feel like sh t',
'import poll pl vote',
'i have to deal with my veri first breakup while deal with my depress in a middl of a lockdown i don t think i can i don t think i ll ever get past thi feel of worthless he left me he left me',
'be more grate',
'substitut addict',
'my parent are tri to take my phone and comput out of my room at m',
'realli depress',
'hat hob',
'do you have experi with mental health mobil applic a short questionnair for my dissert thesi',
'my ex boyfriend kill himself and i don t know how to deal with it whilst be in a new relationship',
'go from a zte phone to a s is so insan',
'i will never be enough',
'what should i restrict my screen time to',
'i handl stress by do someth more stress',
'i wish i wa a littl bit better',
'hot take by bowl for soup is a direct sequel to by georg orwel',
'friendli remind that they might be giant is the offici band of just post and vice versa',
'cold shower',
'fun fact i have never met a scorpion',
'i feel like i m drown and no one care',
'bro i havent post sinc last year',
'i want a mango berri much',
'i hate mother s day',
'i drew a frog',
'a preview of my stori of opiat addict and overcom all odd',
'whi the heck togepi is so cute',
'anyon els can t write to there full abil',
'on the subject of ryan post',
'women amirit',
'i just close reddit look around my room and open it again',
'how do i talk to my parent about hide the adderal in the hous',
'idk anymor',
'forgot to ask for her number',
'thi year ha gone by realli fast',
'tip on how to deal with difficult parent',
'i feel incred guilti anytim i buy myself someth even remot expens even though i paid for it with my own money',
'i have no chill',
'i get so stress in class',
'tell me a reason whi i m not retard',
'just post',
'hi what did you have for breakfast today',
'went to jail still can t stop use meth',
'kaijun wing unrel i absolut hate top gun',
'insuffl of dmt',
'warn veri scari post actual scari thi time',
'whi the hell doe suffer exist',
'i have veri littl save but won t starv i have a home with ac pc and ps but everyday is so tire',
'a relax guid medit for stress',
'my battl with addict',
'here again i don t know if i can make it',
'nge on netflix like',
'i owe a hospit bill and i can t pay it and there s so much go on i need someon to talk to',
'type but not realli type the post',
'start full time work ha me regress back into anxiou thought pattern',
'hey',
'boil bodi',
'i m play red dead redempt for the first time',
'is it weird that i enjoy plain toast',
'i ve f been smoke hash for the past year or so and i ve been tri to quit late but i just never seem to get there',
'i m have intrus thought about a dumb situat',
'i wish i d get corona so my mom could shut the up',
'i m stress about my upcom birthday',
'suffer speak',
'that new ariana grand justin bieber song broke me down',
'd eleph anim',
'buy pepsi',
'anyon els wake up with anxieti',
'one step short of theft',
'let me out plz human',
'whi doe lust exist',
'inform poll doe the m ald schezuan sauc tast like a sweet and sour sauc with soy sauc flavor',
'i hate my health anxieti',
'sunbowl everyday',
'ok i may be extrem unhing but',
'free mental techniqu for get rid of stress',
'stress in univers',
'public speak when you have social anxieti',
'off my chest i hate bad dag owner',
'sleep is oppress',
'afraid of relaps ask for advis',
'hol up',
'hey r just post which one do you think is the best',
'how valu differ from ethic and moral',
'hello sorri for bad english',
'the best way i ve found to recogn bad journal is three fold',
'kjune nightmar so some love for my favorit game of all time bloodborn',
'jill is short for jilliam',
'what cannabi strain work best for stress relief'] 
    
    train_text.insert(0,cleaned_text[0])
    tokenizer.fit_on_texts(train_text)
    # Get our training data word index
    word_index = tokenizer.word_index
    # Encode training data sentences into sequences
    train_sequences = tokenizer.texts_to_sequences(train_text)
    test_sequences = tokenizer.texts_to_sequences(cleaned_text)
    # Pad the training sequences
    train_seq = pad_sequences(train_sequences, padding=pad_type, truncating=trunc_type, maxlen=65)
    test_seq = pad_sequences(test_sequences, padding=pad_type, truncating=trunc_type, maxlen=65)
    
    #Load best model and weights
    json_file=open('bestmodel.json','r')
    loaded_model_json=json_file.read()
    json_file.close()
    best_model=model_from_json(loaded_model_json)
    best_model.load_weights('weights.best.hdf5')
    
    #Predictions
    print(best_model.predict(test_seq))
    
    model_output= np.round(best_model.predict(test_seq),0).astype(int)
    print(model_output)
    if model_output == 1 :
        output_feeling = "distressed"
    else:
        output_feeling= "fine"

    return render_template('result.html',prediction=model_output)
    #return render_template('index.html', output=f"It looks like you are {output_feeling}.")
    #----------------------------------------------

if __name__ =="__main__":
    app.run(debug=True)